import os
import logging
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel

from backend.services.context_manager import build_base_system_prompt
from backend.services.model_router import stream_chat

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/openclaw", tags=["openclaw_bridge"])

class TalkRequest(BaseModel):
    message: str
    persona_type: Optional[str] = "simplified"
    history: Optional[List[Dict[str, str]]] = []

class SandboxReadRequest(BaseModel):
    filename: str

class SandboxWriteRequest(BaseModel):
    filename: str
    content: str

def _get_sandbox_dir() -> str:
    """Resolve and return the absolute path to data/materials/Sandbox."""
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    sandbox_dir = os.path.realpath(os.path.join(project_root, "data", "materials", "Sandbox"))
    os.makedirs(sandbox_dir, exist_ok=True)
    return sandbox_dir

def _validate_sandbox_path(filename: str) -> str:
    """Verify that the target filename stays within the Sandbox boundary using os.path.commonpath."""
    sandbox_dir = _get_sandbox_dir()
    target_path = os.path.realpath(os.path.join(sandbox_dir, filename))
    
    try:
        if os.path.commonpath([sandbox_dir, target_path]) != sandbox_dir:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"GUARDRAIL BLOCKED: Sandbox boundary violation. Cannot access path outside {sandbox_dir}."
            )
        if target_path == sandbox_dir:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="GUARDRAIL BLOCKED: Cannot modify or read the sandbox directory itself as a file."
            )
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="GUARDRAIL BLOCKED: Sandbox boundary violation across different storage drives."
        )
    return target_path

@router.post("/talk")
def talk_endpoint(payload: TalkRequest):
    """
    Bi-directional bridge endpoint for OpenClaw to converse with the classroom engine.
    Receives a message from OpenClaw, routes through the system context manager, and returns clean text response.
    """
    if not payload.message or not payload.message.strip():
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Message content cannot be empty.")

    try:
        system_prompt, kb_count, mem_count = build_base_system_prompt(
            last_user_msg=payload.message,
            persona_type=payload.persona_type or "simplified"
        )
        
        messages_list = list(payload.history or [])
        messages_list.append({"role": "user", "content": payload.message})

        logger.info(f"OpenClaw talk endpoint invoked. KB hits: {kb_count}, Memory hits: {mem_count}")
        
        full_reply = ""
        for chunk in stream_chat(messages_list, system_prompt):
            if isinstance(chunk, dict) and "text" in chunk:
                full_reply += chunk["text"]
            elif isinstance(chunk, str):
                full_reply += chunk

        return {
            "status": "success",
            "reply": full_reply.strip() or "No response generated by model.",
            "meta": {
                "kb_hits": kb_count,
                "memory_hits": mem_count
            }
        }
    except Exception as e:
        logger.exception(f"Error executing talk endpoint for OpenClaw: {str(e)}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Engine execution failure: {str(e)}")

@router.get("/sandbox/list")
def list_sandbox():
    """List all available files in the sandbox directory via SandboxVFS."""
    try:
        from backend.services.sandbox_vfs import sandbox_vfs
        files = sandbox_vfs.list_files()
        return {
            "status": "success",
            "count": len(files),
            "files": files
        }
    except Exception as e:
        logger.error(f"Failed to list sandbox directory: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@router.post("/sandbox/read")
def read_sandbox(payload: SandboxReadRequest):
    """Read file contents from the sandbox via SandboxVFS boundary validation."""
    if not payload.filename:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Filename is required.")

    from backend.services.sandbox_vfs import sandbox_vfs, SandboxVFSError
    try:
        content = sandbox_vfs.read_file(payload.filename)
        return {
            "status": "success",
            "filename": payload.filename,
            "content": content
        }
    except SandboxVFSError as e:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(e))
    except FileNotFoundError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))
    except Exception as e:
        logger.error(f"Error reading sandbox file {payload.filename}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@router.post("/sandbox/write")
def write_sandbox(payload: SandboxWriteRequest):
    """Write or update file contents in the sandbox via SandboxVFS boundary validation."""
    if not payload.filename:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Filename is required.")

    from backend.services.sandbox_vfs import sandbox_vfs, SandboxVFSError
    try:
        sandbox_vfs.write_file(payload.filename, payload.content)
        return {
            "status": "success",
            "filename": payload.filename,
            "message": f"Successfully wrote {len(payload.content)} characters to sandbox file {payload.filename}."
        }
    except SandboxVFSError as e:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(e))
    except Exception as e:
        logger.error(f"Error writing to sandbox file {payload.filename}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

